version: '3'

services:
  wp:
    image: wordpress:latest
    container_name: wp
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal
      - traefik
    labels:
      # traefik V2
      - traefik.http.routers.wp.rule=Host(`${SITE_URL}`)

      # traefik V1
      # - traefik.backend=wp
      # - traefik.frontend.rule=Host:${SITE_URL}
      # - traefik.docker.network=traefik
      # - traefik.port=80
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  traefik:
    external: true
  internal:
    external: false

